server:
  port: 8760
spring:
  application:
    name: yacht-club
  freemarker:
#    prefix: classpath:/templates/
    suffix: .ftl
    cache: false
    content-type: text/html
    template-loader-path: classpath:/templates/

  redis:
    host: localhost
    shiro:
      host: localhost
      port: 6379
      timeout: 0
      password:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/yacht_club?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    min-idle: 5
    max-active: 20
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,config,log4j
    use-global-data-source-stat: true
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    filter:
      wall:
        config:
          multi-statement-allow: true

mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml

logging:
    level:
        com.id0304.dao: debug

yachtImg:
  prefix: D://yachtImg/
  suffix: .jpg

homeImg:
  prefix: D://yachtImg/homeImg/
  suffix: .png

orderFtlAddress:  D://orderFtl/

memberOrdersAddress: D://orderFtl/memberOrders/

payFinishBackUrl: http://localhost:8080/#/user

